/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: abettini <abettini@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/05/10 09:46:44 by abettini          #+#    #+#             */
/*   Updated: 2024/01/23 14:52:18 by abettini         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

int	g_exit_code = 0;

static void	ft_sighandler(int signal)
{
	if (signal == CTRL_C)
	{
		write(1, "\n", 1);
		rl_replace_line("", 0);
		rl_on_new_line();
		rl_redisplay();
		g_exit_code = 130;
	}
}

static void	ft_init(t_msh *msh, t_list **vars, t_list **cmd, char **env)
{
	*cmd = NULL;
	*vars = ft_env_from_matrix_to_list(env);
	msh->vars = vars;
	msh->cmd = cmd;
	msh->exit = 0;
	msh->std[0] = dup(STDIN_FILENO);
	msh->std[1] = dup(STDOUT_FILENO);
	msh->fd[0] = -2;
	msh->fd[1] = -2;
}

static void	ft_loop(t_msh *msh)
{
	char	*str;

	while (!msh->exit)
	{
		signal(CTRL_C, ft_sighandler);
		signal(CTRL_BS, SIG_IGN);
		str = readline("$ ");
		if (!str)
			break ;
		else if (*str && !ft_check_cmd_err(str))
		{
			ft_parsing(str, msh);
			g_exit_code = ft_pipes(msh->cmd, msh);
			ft_lstclear(msh->cmd, ft_free_cmdnode);
			*msh->cmd = NULL;
		}
		else if (*str)
			g_exit_code = 2;
		if (*str)
			add_history(str);
		free(str);
	}
	ft_lstclear(msh->vars, ft_free_varsnode);
	rl_clear_history();
}

//(prints the list of nodes (after parsing))
//ft_print_lst(*msh->cmd);

int	main(int ac, char **av, char **env)
{
	t_list	*cmd;
	t_list	*vars;
	t_msh	msh;

	(void)ac;
	(void)av;
	ft_init(&msh, &vars, &cmd, env);
	ft_loop(&msh);
	ft_putstr_fd("exit\n", 1);
	ft_close_fds(msh.std[0], msh.std[1]);
	return (g_exit_code);
}

/*
	//---history_list---
	//This function returns a pointer to the history list.
	//The 42_minishell's subject doesn't allow its use.
	 
	HIST_ENTRY **mylist = history_list();
	free(mylist);

	//Instead, we chose to suppress the leaks
	//generated by the add_history function.
*/
